name: Base Tests Chrome
#on: [push]
on:
  push:
    branches:
      - test
jobs:
  base-test-chrome-linux-run:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: base-test-chrome-linux-run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          record: true
          # edge, firefox
          browser: chrome
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  base-test-firefox-linux-run:
    # ubuntu-latest - Firefox, windows-latest - edge, ubuntu-20.04 -chrome
    runs-on: ubuntu-latest
    needs:  [base-test-electron-linux-run]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: base-test-firefox-linux-run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          record: true
          # edge, firefox
          browser: firefox
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_SECRET_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}